import { afterEach, beforeEach, expect, it } from "vitest";
import { mkdtemp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import sharp from "sharp";
import { randomUUID, createHash } from "node:crypto";
import { createCutout, resolveCutout } from "../server/main-image-cutouts";
import { changeMainImage, getTopDownState, preserveMainOriginal, restoreCutoutPolygon } from "../server/main-image-tools";
import { TOP_DOWN_SHOT_ID } from "../shared/main-image-tools";
import { makeAssetRecord, writeGeneratedAsset } from "./test-utils";
import { isGalleryEligibleAsset } from "../server/gallery-store";
let root:string,source:Buffer;
const hash=(data:Buffer)=>createHash("sha256").update(data).digest("hex");
beforeEach(async()=>{root=await mkdtemp(path.join(tmpdir(),"main-tools-"));await mkdir(path.join(root,"rug"));source=await sharp({create:{width:80,height:80,channels:4,background:"#f0e8d8"}}).png().toBuffer();await writeFile(path.join(root,"rug","base.png"),source);});
afterEach(async()=>{await rm(root,{recursive:true,force:true});});
it("restores only the lasso interior from original pixels; preserves parents and deduplicates saves",async()=>{
 const cutout=await sharp({create:{width:80,height:80,channels:4,background:"transparent"}}).png().toBuffer();
 const id=randomUUID();await createCutout(root,"rug",id,"test",async()=>({image:cutout,uncertainty:null}));
 const input={requestId:randomUUID(),points:[{x:.25,y:.25},{x:.75,y:.25},{x:.75,y:.75},{x:.25,y:.75}]};
 const repaired=await restoreCutoutPolygon(root,id,input);
 expect(repaired).toMatchObject({parentId:id,approved:false,provider:"manual",sourceSha256:hash(source)});
 expect(await restoreCutoutPolygon(root,id,input)).toEqual(repaired);
 const result=await resolveCutout(root,"rug",repaired.id,hash(source),false);
 const pixels=await sharp(result.file).ensureAlpha().raw().toBuffer();
 expect([...pixels.subarray((40*80+40)*4,(40*80+40)*4+4)]).toEqual([240,232,216,255]);
 const originalCutout=await sharp(cutout).raw().toBuffer();
 let outsideMatches=true;for(let y=0;y<80;y++)for(let x=0;x<80;x++)if(x<19||x>61||y<19||y>61)outsideMatches&&=pixels.subarray((y*80+x)*4,(y*80+x)*4+4).equals(originalCutout.subarray((y*80+x)*4,(y*80+x)*4+4));
 expect(outsideMatches).toBe(true);
 expect(await readFile((await resolveCutout(root,"rug",id,hash(source),false)).file)).toEqual(cutout);
 expect(await readFile(path.join(root,"rug","base.png"))).toEqual(source);
 await expect(restoreCutoutPolygon(root,id,{...input,points:[{x:0,y:0},{x:1,y:0},{x:1,y:1}]})).rejects.toMatchObject({code:"REPAIR_ID_REUSED"});
 expect(()=>restoreCutoutPolygon(root,id,{requestId:randomUUID(),points:[{x:-1,y:0},{x:1,y:0},{x:1,y:1}]})).toThrow();
 await writeFile(path.join(root,"rug","base.png"),await sharp(source).negate().png().toBuffer());
 await expect(restoreCutoutPolygon(root,id,{...input,requestId:randomUUID()})).rejects.toMatchObject({code:"CUTOUT_SOURCE_CHANGED"});
},60000);
it("accepts only top-down candidates, retries from the preserved original, and restores exact original bytes",async()=>{
 const saved=await preserveMainOriginal(root,"rug");expect(saved.sha256).toBe(hash(source));
 const asset=makeAssetRecord({productId:"rug",shotId:TOP_DOWN_SHOT_ID,assetId:"top-down-candidate",status:"done"});asset.inputs.baseImage.sha256=saved.sha256;
 const generated=await writeGeneratedAsset(root,asset);const changed=await sharp(source).negate().png().toBuffer();await writeFile(generated.imagePath,changed);
 expect(isGalleryEligibleAsset({...asset,status:"accepted"})).toBe(false);
 expect((await getTopDownState(root,"rug")).candidates).toHaveLength(1);
 const accepted=await changeMainImage(root,"rug",saved.sha256,asset.assetId);
 expect(accepted.sourceSha256).not.toBe(saved.sha256);
 expect(await readFile(saved.file)).toEqual(source);
 expect((await preserveMainOriginal(root,"rug")).sha256).toBe(saved.sha256);
 expect((await getTopDownState(root,"rug")).canRestore).toBe(true);
 await expect(changeMainImage(root,"rug",saved.sha256)).rejects.toMatchObject({code:"SOURCE_CHANGED"});
 await changeMainImage(root,"rug",accepted.sourceSha256);
 expect(await readFile(path.join(root,"rug","base.png"))).toEqual(source);
 expect((await getTopDownState(root,"rug")).canRestore).toBe(false);
},60000);
it("never replaces a missing original backup with a later image",async()=>{
 const saved=await preserveMainOriginal(root,"rug");await rm(saved.file);
 await expect(preserveMainOriginal(root,"rug")).rejects.toMatchObject({code:"ORIGINAL_MISSING"});
 expect(await readFile(path.join(root,"rug","base.png"))).toEqual(source);
},60000);

it("imports retouched images, preserves transparency, rejects bad uploads and restores the original",async()=>{
 const saved=await preserveMainOriginal(root,"rug");
 await expect(changeMainImage(root,"rug",saved.sha256,undefined,Buffer.from("not an image"))).rejects.toMatchObject({code:"INVALID_IMAGE"});
 expect(await readFile(path.join(root,"rug","base.png"))).toEqual(source);
 const upload=await sharp({create:{width:100,height:70,channels:4,background:{r:200,g:100,b:50,alpha:.5}}}).png().toBuffer();
 const result=await changeMainImage(root,"rug",saved.sha256,undefined,upload);
 expect(result.cutout).toMatchObject({approved:false,provider:"manual",sourceSha256:result.sourceSha256});
 const resolved=await resolveCutout(root,"rug",result.cutout!.id,result.sourceSha256,false);
 expect((await sharp(resolved.file).stats()).isOpaque).toBe(false);
 expect(await readFile(saved.file)).toEqual(source);
 await expect(changeMainImage(root,"rug",saved.sha256,undefined,upload)).rejects.toMatchObject({code:"SOURCE_CHANGED"});
 await changeMainImage(root,"rug",result.sourceSha256);
 expect(await readFile(path.join(root,"rug","base.png"))).toEqual(source);
},60000);
